export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
       <h1>🔥 testing pipeline</h1>
        {children}
        <footer>© 2025</footer></body>
    </html>
  )
}
